FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install
# RUN npm ci --only=production

# Bungle
COPY . .

EXPOSE 3000
CMD ["node", "main.js"]